coldkitchen:
    resource: "@ColdkitchenBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"