# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
            - { name: twig.extension }

    coldkitchen_bundle.image_type_extension:
        class: ColdkitchenBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }