<?php

namespace ColdkitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchtergrondFotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchtergrondFotoRepository extends EntityRepository
{
}
