<?php

namespace ColdkitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PartnerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerTypeRepository extends EntityRepository
{
	public function findFieldpartners(){
		$id = 1;
		return $this->filterOpType($id);
	}

	public function findSuppliers(){
		$id = 2;

		return $this->filterOpType($id);
	}
	public function findPartners(){
		$id = 3;
		return $this->filterOpType($id);
	}
	public function findSponsors(){
		
		$id = 4;

		return $this->filterOpType($id);
	}

	public function filterOpType($id){
		$query = $this->getEntityManager()
        	->createQuery("SELECT p FROM ColdkitchenBundle:Partner p WHERE p.typepartner = :id AND p.zichtbaar = 1")
        	->setParameter('id', $id);

        try {
	        return $query->getResult();;
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }

		return $qb->getQuery()->getResult();
	}

	
}
