<?php

namespace ColdkitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PloegRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PloegRepository extends EntityRepository
{
}
