<?php

namespace ColdkitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpelerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpelerRepository extends EntityRepository
{
}
