<?php

namespace ColdkitchenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpelerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpelerRepository extends EntityRepository
{
	public function findByPloegAndNummer($ploegid,$spelernummer){

		$query = $this->createQueryBuilder('s')
		    ->where('s.spelernummer = :spelernummer')
		    ->andWhere('s.ploeg = :ploegid')
		    ->setParameter('spelernummer', $spelernummer)
		    ->setParameter('ploegid', $ploegid)
		    ->getQuery();


		return($query->getOneOrNullResult());

	}
}
